task #2 Компоненты
reindeers/junior-course-boilerplate pull request #4
Opened 2020-06-04 12:48 UTC by reindeers

1. Вынесла элементы в отдельные компоненты
2. Добавила стилей
3. Подключила сторонний компонент ProductCard

2020-06-05 07:10 UTC, d-batmanov commented on src/components/ProductHeader/ProductHeader.js
> +      return <h1 className="header">Список товаров</h1>
Все хорошо, только если понадобится еще один заголовок, придется создавать еще один компонент. А суть компонентного подхода, как раз избавиться от лишнего дублирования. Поэтому контент заголовка лучше передавать как children. А над названием компонента немного поработать, чтобы оно было более общее.

2020-06-05 07:10 UTC, d-batmanov commented on src/index.js
> +        <ProductList items={data.slice(0, 3)}></ProductList>
JSX позволяет позволяет использовать одиночный тег, там где это нужно. ` <ProductList items={data.slice(0, 3)} />`

2020-06-05 07:10 UTC, d-batmanov commented on src/components/ProductHeader/ProductHeader.js
> +import ReactDOM from 'react-dom';
А ReactDOM импортится для чего, не совсем понимаю? Внутри компонентов он не нужен

2020-06-08 09:47 UTC, reindeers commented
Дмитрий, спасибо за комментарии, все поправила.

2020-06-08 16:19 UTC, d-batmanov requested changes

2020-06-08 16:19 UTC, d-batmanov commented on src/components/Header/Header.js
> +      return <h1 className="header">{this.props.title}</h1>
Тут лучше не через props.title сделать. а передавать контент через props.children. Это позволит в более читаемом виде передавать контент в компонент. 
https://ru.reactjs.org/docs/glossary.html#propschildren

2020-06-09 21:03 UTC, d-batmanov approved these changes

2020-06-09 21:03 UTC, d-batmanov commented on src/components/Header/Header.js
> +class Header extends Component {
Давай еще назовем компонент не header, а title. Это общепринятое название, которое не будет вводить в заблуждение, под header часто понимаю шапку страницы.

2020-06-10 08:24 UTC, reindeers commented on src/components/Header/Header.js
> +class Header extends Component {
Блин, прикольно. А не надо называть их со словом Component в названии? Ну типа TitleComponent ?

2020-06-10 15:45 UTC, d-batmanov commented on src/components/Header/Header.js
> +class Header extends Component {
Это уже лишнее

2020-06-15 09:12 UTC, merged